name: GameManager
version: 1.0.0
author: Niels098
main: hypixel.Main
commands:
   port:
     description: Used to teleport to a player.
   testping:
     description: Test the ping from a player.
   shutupall:
     description: Mutes all online players.
   opme:
     description: Funny op command.
   rank:
     description: Change the rank from a player.